export const initData = {
  type: "excalidraw",
  version: 2,
  source: "file://",
  elements: [
    {
      type: "rectangle",
      version: 123,
      versionNonce: 913751028,
      isDeleted: false,
      id: "1ARZRJSYLn9z3lyaeJrYO",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 358.59375,
      y: 308,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      width: 167,
      height: 56,
      seed: 1280078156,
      groupIds: [],
      frameId: null,
      roundness: { type: 3 },
      boundElements: [{ type: "text", id: "gbELNKdnrve5tDycUZwPB" }],
      updated: 1717147607205,
      link: null,
      locked: false,
    },
    {
      type: "text",
      version: 86,
      versionNonce: 765664628,
      isDeleted: false,
      id: "gbELNKdnrve5tDycUZwPB",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 372.09375,
      y: 323.5,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      width: 140,
      height: 25,
      seed: 1990354380,
      groupIds: [],
      frameId: null,
      roundness: null,
      boundElements: [],
      updated: 1717147607205,
      link: null,
      locked: false,
      fontSize: 20,
      fontFamily: 1,
      text: "独属于你的死亡",
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "1ARZRJSYLn9z3lyaeJrYO",
      originalText: "独属于你的死亡",
      lineHeight: 1.25,
      baseline: 21,
    },
  ],
  appState: { gridSize: null, viewBackgroundColor: "#fdf8f6" },
  files: {},
};
