export const initData = {
  type: "excalidraw",
  version: 2,
  source: "file://",
  elements: [
    {
      type: "rectangle",
      version: 123,
      versionNonce: 913751028,
      isDeleted: false,
      id: "1ARZRJSYLn9z3lyaeJrYO",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 358.59375,
      y: 308,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      width: 167,
      height: 56,
      seed: 1280078156,
      groupIds: [],
      frameId: null,
      roundness: { type: 3 },
      boundElements: [{ type: "text", id: "gbELNKdnrve5tDycUZwPB" }],
      updated: 1717147607205,
      link: null,
      locked: false,
    },
    {
      type: "text",
      version: 86,
      versionNonce: 765664628,
      isDeleted: false,
      id: "gbELNKdnrve5tDycUZwPB",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      angle: 0,
      x: 372.09375,
      y: 323.5,
      strokeColor: "#1e1e1e",
      backgroundColor: "transparent",
      width: 140,
      height: 25,
      seed: 1990354380,
      groupIds: [],
      frameId: null,
      roundness: null,
      boundElements: [],
      updated: 1717147607205,
      link: null,
      locked: false,
      fontSize: 20,
      fontFamily: 1,
      text: "独属于你的死亡",
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "1ARZRJSYLn9z3lyaeJrYO",
      originalText: "独属于你的死亡",
      lineHeight: 1.25,
      baseline: 21,
    },
  ],
  appState: { gridSize: null, viewBackgroundColor: "#fdf8f6" },
  files: {},
};

export const initCircleItems = [
  { color: "#8A2BE2", time: "12-18岁", content: "暗焰青春" },
  { color: "#8A2BE2", time: "18-24岁", content: "命运迷途" },
  { color: "#8A2BE2", time: "24-30岁", content: "魅影红尘" },
  { color: "#8A2BE2", time: "30-36岁", content: "繁星梦旅" },
  { color: "#8A2BE2", time: "36-42岁", content: "梦幻盛景" },
  { color: "#8A2BE2", time: "42-48岁", content: "灵魂莲华" },
  { color: "#8A2BE2", time: "48-54岁", content: "幽冥之舞" },
  { color: "#8A2BE2", time: "54-60岁", content: "暮色挽歌" },
  { color: "#8A2BE2", time: "60-66岁", content: "永夜序曲" },
  { color: "#8A2BE2", time: "66-72岁", content: "永恒终焉" },
  { color: "#8A2BE2", time: "0-6岁", content: "幽冥之初" },
  { color: "#8A2BE2", time: "6-12岁", content: "迷雾晨曦" },
];
